version: '3.8'

services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d:ro
    depends_on:
      - app

  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    image: infra-demo_app:latest
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    labels:
      - "prometheus.enable=true"
      - "prometheus.port=3000"
      - "prometheus.path=/metrics"

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=demo
      - POSTGRES_PASSWORD=demo
      - POSTGRES_DB=demo
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  
  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    depends_on:
      - app
  
  grafana:
    image: grafana/grafana-oss:latest
    ports:
      - "3001:3000"
    environment:
      - GF_SERVER_ROOT_URL=http://localhost:3001
    depends_on:
      - prometheus

volumes:
  db_data:
