# infra-demo/prometheus.yml

global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  # 1) 애플리케이션 메트릭 수집
  - job_name: 'app'
    metrics_path: /metrics
    static_configs:
      - targets: ['app:3000']

  # 2) (옵션) Nginx 상태 → exporter를 별도 띄웠다면 이렇게 추가
  # - job_name: 'nginx'
  #   metrics_path: /metrics
  #   static_configs:
  #     - targets: ['nginx-exporter:9113']

  # 3) (옵션) PostgreSQL exporter를 사용한다면
  # - job_name: 'postgres'
  #   static_configs:
  #     - targets: ['postgres-exporter:9187']
